In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as pt

In [2]:
data=pd.read_csv("Social_Network_Ads.csv")
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
data.shape



(400, 5)

In [4]:
ismale=pd.get_dummies(data['Gender'],drop_first=True)
data=pd.concat([data,ismale],axis=1)
data.head()


User ID  Gender  Age  EstimatedSalary  Purchased  Male
0  15624510    Male   19            19000          0     1
1  15810944    Male   35            20000          0     1
2  15668575  Female   26            43000          0     0
3  15603246  Female   27            57000          0     0
4  15804002    Male   19            76000          0     1

In [5]:
data.corr()

User ID       Age  EstimatedSalary  Purchased      Male
User ID          1.000000 -0.000721         0.071097   0.007120 -0.025249
Age             -0.000721  1.000000         0.155238   0.622454 -0.073741
EstimatedSalary  0.071097  0.155238         1.000000   0.362083 -0.060435
Purchased        0.007120  0.622454         0.362083   1.000000 -0.042469
Male            -0.025249 -0.073741        -0.060435  -0.042469  1.000000

In [6]:
x=(data[['Age','EstimatedSalary',]]).values
y=(data['Purchased']).values


In [7]:
#normalization

x=(x-np.mean(x))/np.std(x)

#biasing
x = np.column_stack((np.ones((x.shape[0],1)),x))


In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=20)

In [9]:
def sig(z):
    return 1/(1+np.exp(-z))

In [10]:
def loss(yp,y):
    return (-1/y.shape[0])*(y.T@np.log(yp)+(1-y).T@np.log(1-yp))

In [11]:

B = np.zeros((x_train.shape[1],1))
print(B)
alpha =3.4
L =[]
y_train=y_train.reshape(x_train.shape[0],-1)
for i in range(2000):
  k = x_train@B
  z = sig(k)
  dB = (1/x_train.shape[0])*np.dot(x_train.T,(z-y_train))
  B = B-dB*alpha
  L.append(loss(z,y_train))
print(L)

[[0.]
 [0.]
 [0.]]
[array([[0.69314718]]), array([[0.65460577]]), array([[0.63159802]]), array([[0.62328535]]), array([[0.61501954]]), array([[0.61120018]]), array([[0.60671368]]), array([[0.60409318]]), array([[0.60137387]]), array([[0.59958794]]), array([[0.59793176]]), array([[0.59678064]]), array([[0.5957818]]), array([[0.59506561]]), array([[0.59446706]]), array([[0.59402929]]), array([[0.59367138]]), array([[0.59340589]]), array([[0.59319178]]), array([[0.59303125]]), array([[0.59290296]]), array([[0.59280598]]), array([[0.59272897]]), array([[0.59267038]]), array([[0.59262406]]), array([[0.59258865]]), array([[0.59256075]]), array([[0.59253934]]), array([[0.59252252]]), array([[0.59250957]]), array([[0.59249941]]), array([[0.59249157]]), array([[0.59248544]]), array([[0.59248069]]), array([[0.59247698]]), array([[0.59247411]]), array([[0.59247186]]), array([[0.59247012]]), array([[0.59246876]]), array([[0.5924677]]), array([[0.59246687]]), array([[0.59246623]]), array([[0.592465

In [12]:
print(B)

[[-0.61226029]
 [ 0.96763206]
 [ 0.85404099]]


In [13]:
k=x_test@B
y_pre=sig(k)
for i in range(y_pre.shape[0]):
  if y_pre[i]>=0.53:
    y_pre[i]=1
  else :
    y_pre[i]=0
y_pre=y_pre.reshape(-1)

In [14]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pre)
print(cm)

[[45  0]
 [18 17]]


In [15]:
acc = (45+17)/(45+17+18)
print(acc)

0.775
