In [2]:
import pandas as pd
import numpy as np


In [6]:
df=pd.read_csv('kc_house_data.csv')
df.head()


id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [16]:
x=df.loc[:,'bedrooms':]
#all rows and coloum 3 to end
x=np.array(x)
y=df.price
y=np.array(y)
#adding bias term of 1 to x in coloumn 1
n=len(df['id'])
b=np.ones([n,1])
np.shape(b)
#result = np.hstack((b, np.atleast_2d(x).T)) 
r = np.column_stack((b, x)) 
r

array([[ 1.00000e+00,  3.00000e+00,  1.00000e+00, ..., -1.22257e+02,
         1.34000e+03,  5.65000e+03],
       [ 1.00000e+00,  3.00000e+00,  2.25000e+00, ..., -1.22319e+02,
         1.69000e+03,  7.63900e+03],
       [ 1.00000e+00,  2.00000e+00,  1.00000e+00, ..., -1.22233e+02,
         2.72000e+03,  8.06200e+03],
       ...,
       [ 1.00000e+00,  2.00000e+00,  7.50000e-01, ..., -1.22299e+02,
         1.02000e+03,  2.00700e+03],
       [ 1.00000e+00,  3.00000e+00,  2.50000e+00, ..., -1.22069e+02,
         1.41000e+03,  1.28700e+03],
       [ 1.00000e+00,  2.00000e+00,  7.50000e-01, ..., -1.22299e+02,
         1.02000e+03,  1.35700e+03]])

In [9]:
beta = r.T@r
beta = np.linalg.pinv(beta)@r.T@y
beta

array([ 7.25457893e+01, -3.55112009e+04,  4.10548961e+04,  1.10264002e+02,
        1.33383087e-01,  5.26156004e+03,  5.83295394e+05,  5.23552277e+04,
        2.72094262e+04,  9.54805279e+04,  7.13929342e+01,  3.88715867e+01,
       -2.56179589e+03,  2.04186942e+01, -5.19076331e+02,  6.02189076e+05,
       -2.17900343e+05,  2.30994307e+01, -3.76111345e-01])

In [10]:
y_pred=r@beta
y_pred

array([214165.2493449 , 736050.03152291, 376774.44328167, ...,
       147579.54750097, 381526.70103768, 150168.61208116])

In [12]:
y_mean = np.mean(y)
R2 = (y_pred - y_mean).T@(y_pred - y_mean)/((y - y_mean).T@(y - y_mean))
R2

0.6996864627832613

In [20]:
mse = (y_pred-y).T@(y_pred-y)/len(df.index)
print(np.sqrt(mse))

201188.15995950662
