In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('kc_house_data.csv')
dataset.head()

id             date     price  ...     long  sqft_living15  sqft_lot15
0  7129300520  20141013T000000  221900.0  ... -122.257           1340        5650
1  6414100192  20141209T000000  538000.0  ... -122.319           1690        7639
2  5631500400  20150225T000000  180000.0  ... -122.233           2720        8062
3  2487200875  20141209T000000  604000.0  ... -122.393           1360        5000
4  1954400510  20150218T000000  510000.0  ... -122.045           1800        7503

[5 rows x 21 columns]

In [3]:
x = np.array(dataset.iloc[:, 3:])
y = np.array(dataset[['price']])
np.column_stack((np.ones((x.shape[0],1)), x))

array([[ 1.00000e+00,  3.00000e+00,  1.00000e+00, ..., -1.22257e+02,
         1.34000e+03,  5.65000e+03],
       [ 1.00000e+00,  3.00000e+00,  2.25000e+00, ..., -1.22319e+02,
         1.69000e+03,  7.63900e+03],
       [ 1.00000e+00,  2.00000e+00,  1.00000e+00, ..., -1.22233e+02,
         2.72000e+03,  8.06200e+03],
       ...,
       [ 1.00000e+00,  2.00000e+00,  7.50000e-01, ..., -1.22299e+02,
         1.02000e+03,  2.00700e+03],
       [ 1.00000e+00,  3.00000e+00,  2.50000e+00, ..., -1.22069e+02,
         1.41000e+03,  1.28700e+03],
       [ 1.00000e+00,  2.00000e+00,  7.50000e-01, ..., -1.22299e+02,
         1.02000e+03,  1.35700e+03]])

In [4]:
B = x.T@x
B = np.linalg.pinv(B)@x.T@y
B

array([[-3.55112047e+04],
       [ 4.10549065e+04],
       [ 1.10265938e+02],
       [ 1.33383120e-01],
       [ 5.26154428e+03],
       [ 5.83295385e+05],
       [ 5.23552226e+04],
       [ 2.72094348e+04],
       [ 9.54805235e+04],
       [ 7.13910007e+01],
       [ 3.88696400e+01],
       [-2.56179541e+03],
       [ 2.04186985e+01],
       [-5.19075563e+02],
       [ 6.02189071e+05],
       [-2.17900314e+05],
       [ 2.30994441e+01],
       [-3.76111301e-01]])

In [5]:
y_pred = x@B
y_pred

array([[214165.3078426 ],
       [736050.0534475 ],
       [376774.40150462],
       ...,
       [147579.584567  ],
       [381526.66945122],
       [150168.6486304 ]])

In [6]:
y_mean = np.mean(y)
R2 = (y_pred - y_mean).T@(y_pred - y_mean)/((y - y_mean).T@(y - y_mean))
R2[0][0]


0.6996864639132055

In [7]:
mse = (y_pred-y).T@(y_pred-y)/(y.shape[0])
print(mse[0][0])

40476675919.561584
