In [1]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv(r'C:\Users\Nandhini\Desktop\kc_house_data.csv')
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  6.414100e+09  20141013T000000  221900.0         3       1.00         1180   
1  5.631500e+09  20141209T000000  538000.0         3       2.25         2570   
2  2.487201e+09  20150225T000000  180000.0         2       1.00          770   
3  1.954401e+09  20141209T000000  604000.0         4       3.00         1960   
4  7.237550e+09  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [7]:
x=df.loc[:,'bedrooms':]
x=np.array(x)
y=df.price
y=np.array(y)
n=len(df['id'])
b=np.ones([n,1])
np.shape(b)
r = np.column_stack((b, x)) 
r

array([[ 1.00000e+00,  3.00000e+00,  1.00000e+00, ..., -1.22257e+02,
         1.34000e+03,  5.65000e+03],
       [ 1.00000e+00,  3.00000e+00,  2.25000e+00, ..., -1.22319e+02,
         1.69000e+03,  7.63900e+03],
       [ 1.00000e+00,  2.00000e+00,  1.00000e+00, ..., -1.22233e+02,
         2.72000e+03,  8.06200e+03],
       ...,
       [ 1.00000e+00,  2.00000e+00,  7.50000e-01, ..., -1.22299e+02,
         1.02000e+03,  2.00700e+03],
       [ 1.00000e+00,  3.00000e+00,  2.50000e+00, ..., -1.22069e+02,
         1.41000e+03,  1.28700e+03],
       [ 1.00000e+00,  2.00000e+00,  7.50000e-01, ..., -1.22299e+02,
         1.02000e+03,  1.35700e+03]])

In [8]:
beta = r.T@r
beta = np.linalg.pinv(beta)@r.T@y
beta

array([ 7.26373403e+01, -3.55429632e+04,  4.10775600e+04,  1.10335388e+02,
        1.33179752e-01,  5.27006680e+03,  5.83351203e+05,  5.24194074e+04,
        2.72350588e+04,  9.55767074e+04,  7.14336027e+01,  3.89023039e+01,
       -2.56410181e+03,  2.04290604e+01, -5.19356743e+02,  6.02267193e+05,
       -2.18124701e+05,  2.30910002e+01, -3.75943785e-01])

In [9]:
y_pred=r@beta
y_pred

array([214074.51957573, 736219.99595788, 376666.35611691, ...,
       147409.39063414, 381510.05137396, 150000.68449548])

In [10]:
y_mean = np.mean(y)
R2 = (y_pred - y_mean).T@(y_pred - y_mean)/((y - y_mean).T@(y - y_mean))
R2

0.6996921771474397

In [11]:
mse = (y_pred-y).T@(y_pred-y)/len(df.index)
print(np.sqrt(mse))

201315.03329791233
